name: Fetch and Update Issues JSON

on:
  workflow_dispatch:
  push:
    branches: [main]
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - closed
      - reopened
      - labeled
      - unlabeled
      - milestoned
      - demilestoned
      - typed
      - untyped

permissions:
  contents: write
  issues: read

jobs:
  fetch-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Setup R
        id: setup-r
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ steps.setup-r.outputs.r-version }}-pkgs-v1
          restore-keys: |
            ${{ runner.os }}-r-${{ steps.setup-r.outputs.r-version }}-pkgs-

      - name: Install R script dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/stable")
          pak::pak(c("gh", "glue", "purrr", "jsonlite"))
        shell: Rscript {0}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.ADMIN_PAT }}

      - name: Run script to fetch issues
        run: Rscript .github/scripts/fetch-issues.R
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}

      - name: Commit and push changes to ai branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Create a new 'ai' branch from the current HEAD (main) or reset the existing one.
          git checkout -B ai
          git add .github/ai/issues.json
          git diff --staged --quiet || git commit -m "chore: Update issues.json"
          # Force push the 'ai' branch to the remote, overwriting its history.
          git push --force origin ai
